import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/design/pulse_tokens.dart';
import '../../../core/di/providers.dart';
import '../../../core/errors/app_error.dart';

class ProfileSetupScreen extends ConsumerStatefulWidget { const ProfileSetupScreen({super.key}); @override ConsumerState<ProfileSetupScreen> createState() => _ProfileSetupScreenState(); }
class _ProfileSetupScreenState extends ConsumerState<ProfileSetupScreen> {
  final name = TextEditingController(); bool saving = false; String? error;
  @override void initState() { super.initState(); Future.microtask(_load); Future.microtask(() => ref.read(analyticsServiceProvider).logProfileSetupStarted()); }
  Future<void> _load() async { final state = await ref.read(authServiceProvider).authStateChanges.first; if (!mounted || state.uid == null) return; final user = await ref.read(userRepositoryProvider).getUserModel(state.uid!); if (mounted && user?.displayName != null) name.text = user!.displayName!; }
  Future<void> save() async { final value = name.text.trim(); if (value.length < 2) { setState(() => error = 'enter a name with at least 2 characters.'); return; } if (value.length > 40) { setState(() => error = 'keep your name under 40 characters.'); return; } if (saving) return; setState(() { saving = true; error = null; }); try { final state = await ref.read(authServiceProvider).authStateChanges.first; if (state.uid == null) throw const AuthFailure('session-expired'); await ref.read(userRepositoryProvider).createOrUpdateUser(uid: state.uid!, displayName: value); await ref.read(analyticsServiceProvider).logProfileSetupCompleted(); if (mounted) context.go('/home'); } catch (e) { if (mounted) setState(() { saving = false; error = ErrorMessageMapper.from(e, kind: AppErrorKind.profile).message; }); } }
  @override void dispose() { name.dispose(); super.dispose(); }
  @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: Padding(padding: const EdgeInsets.all(PulseSpace.xl), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Spacer(), Text('set up your Pulse profile', style: AppTypography.display), const SizedBox(height: PulseSpace.md), Text('just your display name for now. your username is created by the existing profile boundary.', style: AppTypography.body.copyWith(color: Theme.of(context).colorScheme.onSurfaceVariant)), const SizedBox(height: PulseSpace.xxl), TextField(controller: name, textInputAction: TextInputAction.done, autofillHints: const [AutofillHints.name], maxLength: 40, decoration: InputDecoration(labelText: 'display name', errorText: error), onSubmitted: (_) => save()), const SizedBox(height: PulseSpace.lg), if (error != null) Semantics(liveRegion: true, child: Text(error!, style: TextStyle(color: Theme.of(context).colorScheme.error))), const SizedBox(height: PulseSpace.sm), SizedBox(width: double.infinity, height: 52, child: FilledButton(onPressed: saving ? null : save, child: saving ? const SizedBox(width: 22, height: 22, child: CircularProgressIndicator(strokeWidth: 2)) : const Text('continue'))), const Spacer()])));
}
